origins = [
    'Astro',
    'Battlecast',
    'Celestial',
    'Chrono',
    'Cybernetic',
    'Dark Star',
    'Mech-Pilot',
    'Rebel',
    'Space Pirate',
    'Star Guardian',
]
classes = [
    'Blademaster',
    'Blaster',
    'Brawler',
    'Demolitionist',
    'Infiltrator',
    'Mana-Reaver',
    'Mystic',
    'Protector',
    'Sniper',
    'Sorceror',
    'Vanguard',
]
low_pop_traits = [
    'Mercenary',
    'Paragon',
    'Starship',
]
trait_champions = {
    'Astro':[
        'nautilus',
        'bard',
        'gnar',
        'teemo',
    ],
    'Battlecast':[
        'illaoi',
        'nocturne',
        'kog',
        'cass',
        'viktor',
        'urgot',
    ],
    'Celestial':[
        'xayah',
        'rakan',
        'xin',
        'ashe',
        'lulu',
    ],
    'Chrono':[
        'caitlyn',
        'tf',
        'blitz',
        'shen',
        'ezreal',
        'riven',
        'wukong',
        'thresh',
    ],
    'Cybernetic':[
        'fiora',
        'leona',
        'lucian',
        'vayne',
        'vi',
        'irelia',
        'ekko',
    ],
    'Dark Star':[
        'j4',
        'morde',
        'karma',
        'shaco',
        'jhin',
        'xerath',
    ],
    'Mech-Pilot':[
        'annie',
        'rumble',
        'fizz',
    ],
    'Rebel':[
        'malphite',
        'ziggs',
        'yasuo',
        'zed',
        'yi',
        'jinx',
        'asol',
    ],
    'Space Pirate':[
        'graves',
        'darius',
        'jayce',
        'gp',
    ],
    'Star Guardian':[
        'poppy',
        'zoe',
        'ahri',
        'neeko',
        'syndra',
        'soraka',
        'janna',
    ],
    'Blademaster':[
        'fiora',
        'xayah',
        'shen',
        'yasuo',
        'yi',
        'irelia',
        'riven',
    ],
    'Blaster':[
        'graves',
        'kog',
        'lucian',
        'ezreal',
        'jinx',
    ],
    'Brawler':[
        'illaoi',
        'malphite',
        'blitz',
        'vi',
        'gnar',
    ],
    'Demolitionist':[
        'ziggs',
        'rumble',
        'gp'
    ],
    'Infiltrator':[
        'nocturne',
        'zed',
        'shaco',
        'fizz',
        'ekko',
    ],
    'Mana-Reaver':[
        'darius',
        'irelia',
        'thresh',
    ],
    'Mercenary':[
        'gp',
    ],
    'Mystic':[
        'bard',
        'cass',
        'karma',
        'soraka',
        'lulu',
    ],
    'Paragon':[
        'janna',
    ],
    'Protector':[
        'j4',
        'rakan',
        'xin',
        'neeko',
        'urgot',
    ],
    'Sniper':[
        'caitlyn',
        'ashe',
        'vayne',
        'jhin',
        'teemo',
    ],
    'Sorceror':[
        'tf',
        'zoe',
        'ahri',
        'annie',
        'syndra',
        'viktor',
        'asol',
    ],
    'Starship':[
        'asol',
    ],
    'Vanguard':[
        'leona',
        'poppy',
        'morde',
        'nautilus',
        'jayce',
        'wukong'
    ],
}

champions_data = {
    'caitlyn':{
        'name':'Caitlyn',
        'cost': 1,
        'thumb':'caitlyn.png',
    },
    'fiora':{
        'name':'Fiora',
        'cost': 1,
        'thumb':'fiora.png',
    },
    'graves':{
        'name':'Graves',
        'cost': 1,
        'thumb':'graves.png',
    },
    'illaoi':{
        'name':'Illaoi',
        'cost': 1,
        'thumb':'illaoi.png',
    },
    'j4':{
        'name':'Jarvan IV',
        'cost': 1,
        'thumb':'j4.png',
    },
    'leona':{
        'name':'Leona',
        'cost': 1,
        'thumb':'leona.png',
    },
    'malphite':{
        'name':'Malphite',
        'cost': 1,
        'thumb':'malphite.png',
    },
    'nocturne':{
        'name':'Nocturne',
        'cost': 1,
        'thumb':'nocturne.png',
    },
    'poppy':{
        'name':'Poppy',
        'cost': 1,
        'thumb':'poppy.png',
    },
    'tf':{
        'name':'TF',
        'cost': 1,
        'thumb':'tf.png',
    },
    'xayah':{
        'name':'Xayah',
        'cost': 1,
        'thumb':'xayah.png',
    },
    'ziggs':{
        'name':'Ziggs',
        'cost': 1,
        'thumb':'ziggs.png',
    },
    'zoe':{
        'name':'Zoe',
        'cost': 1,
        'thumb':'zoe.png',
    },
    'ahri':{
        'name':'Ahri',
        'cost': 2,
        'thumb':'ahri.png',
    },
    'annie':{
        'name':'Annie',
        'cost': 2,
        'thumb':'annie.png',
    },
    'blitz':{
        'name':'Blitz',
        'cost': 2,
        'thumb':'blitz.png',
    },
    'darius':{
        'name':'Darius',
        'cost': 2,
        'thumb':'darius.png',
    },
    'kog':{
        'name':'Kog\'Maw',
        'cost': 2,
        'thumb':'kog.png',
    },
    'lucian':{
        'name':'Lucian',
        'cost': 2,
        'thumb':'lucian.png',
    },
    'morde':{
        'name':'Mordekaiser',
        'cost': 2,
        'thumb':'morde.png',
    },
    'nautilus':{
        'name':'Nautilus',
        'cost': 2,
        'thumb':'nautilus.png',
    },
    'rakan':{
        'name':'Rakan',
        'cost': 2,
        'thumb':'rakan.png',
    },
    'shen':{
        'name':'Shen',
        'cost': 2,
        'thumb':'shen.png',
    },
    'xin':{
        'name':'Xin Zhao',
        'cost': 2,
        'thumb':'xin.png',
    },
    'yasuo':{
        'name':'Yasuo',
        'cost': 2,
        'thumb':'yasuo.png',
    },
    'zed':{
        'name':'Zed',
        'cost': 2,
        'thumb':'zed.png',
    },
    'ashe':{
        'name':'Ashe',
        'cost': 3,
        'thumb':'ashe.png',
    },
    'bard':{
        'name':'Brad',
        'cost': 3,
        'thumb':'bard.png',
    },
    'cass':{
        'name':'Cassiopeia',
        'cost': 3,
        'thumb':'cass.png',
    },
    'ezreal':{
        'name':'Ezreal',
        'cost': 3,
        'thumb':'ezreal.png',
    },
    'jayce':{
        'name':'Jayce',
        'cost': 3,
        'thumb':'jayce.png',
    },
    'karma':{
        'name':'Karma',
        'cost': 3,
        'thumb':'karma.png',
    },
    'yi':{
        'name':'Yi',
        'cost': 3,
        'thumb':'yi.png',
    },
    'neeko':{
        'name':'Neeko',
        'cost': 3,
        'thumb':'neeko.png',
    },
    'rumble':{
        'name':'Rumble',
        'cost': 3,
        'thumb':'rumble.png',
    },
    'shaco':{
        'name':'Shaco',
        'cost': 3,
        'thumb':'shaco.png',
    },
    'syndra':{
        'name':'Syndra',
        'cost': 3,
        'thumb':'syndra.png',
    },
    'vayne':{
        'name':'Vayne',
        'cost': 3,
        'thumb':'vayne.png',
    },
    'vi':{
        'name':'Vi',
        'cost': 3,
        'thumb':'vi.png',
    },
    'fizz':{
        'name':'Fizz',
        'cost': 4,
        'thumb':'fizz.png',
    },
    'gnar':{
        'name':'Gnar',
        'cost': 4,
        'thumb':'gnar.png',
    },
    'irelia':{
        'name':'Irelia',
        'cost': 4,
        'thumb':'irelia.png',
    },
    'jhin':{
        'name':'Jhin',
        'cost': 4,
        'thumb':'jhin.png',
    },
    'jinx':{
        'name':'Jinx',
        'cost': 4,
        'thumb':'jinx.png',
    },
    'riven':{
        'name':'Riven',
        'cost': 4,
        'thumb':'riven.png',
    },
    'soraka':{
        'name':'Soraka',
        'cost': 4,
        'thumb':'soraka.png',
    },
    'teemo':{
        'name':'Teemo',
        'cost': 4,
        'thumb':'teemo.png',
    },
    'viktor':{
        'name':'Viktor',
        'cost': 4,
        'thumb':'viktor.png',
    },
    'wukong':{
        'name':'Wukong',
        'cost': 4,
        'thumb':'wukong.png',
    },
    'asol':{
        'name':'Aurelion Sol',
        'cost': 5,
        'thumb':'asol.png',
    },
    'ekko':{
        'name':'Ekko',
        'cost': 5,
        'thumb':'ekko.png',
    },
    'gp':{
        'name':'Gangplank',
        'cost': 5,
        'thumb':'gp.png',
    },
    'janna':{
        'name':'Janna',
        'cost': 5,
        'thumb':'janna.png',
    },
    'lulu':{
        'name':'Lulu',
        'cost': 5,
        'thumb':'lulu.png',
    },
    'thresh':{
        'name':'Thresh',
        'cost': 5,
        'thumb':'thresh.png',
    },
    'urgot':{
        'name':'Urgot',
        'cost': 5,
        'thumb':'urgot.png',
    },
    'xerath':{
        'name':'Xerath',
        'cost': 5,
        'thumb':'xerath.png',
    },
}
