origins = [
    'A.D.M.I.N',
    'Anima Squad',
    'Civilian',
    'Corrupted',
    'Gadgeteen',
    'LaserCorps',
    'Mecha: PRIME',
    'Ox Force',
    'Star Guardian',
    'Supers',
    'Threat',
    'The Underground',
]
classes = [
    'Ace',
    'Aegis',
    'Arsenal',
    'Brawler',
    'Defender',
    'Duelist',
    'Forecaster',
    'Hacker',
    'Heart',
    'Mascot',
    'Prankster',
    'Recon',
    'Renegade',
    'Spellslinger',
    'Sureshot',
]
low_pop_traits = [
    'Arsenal',
    'Forecaster',
    'Corrupted',
]
trait_champions = {
    'A.D.M.I.N':[
        'blitz',
        'camille',
        'leblanc',
        'soraka',
    ],
    'Anima Squad':[
        'jinx',
        'mf',
        'nasus',
        'riven',
        'sylas',
        'vayne',
    ],
    'Civilian':[
        'galio',
        'janna',
        'sivir',
    ],
    'Corrupted':[
        'fiddle',
    ],
    'Gadgeteen':[
        'annie',
        'lulu',
        'nunu',
        'poppy',
        'zoe',
    ],
    'LaserCorps':[
        'ashe',
        'mord',
        'renekton',
        'sejuani',
        'senna',
        'yasuo',
        'zed',
    ],
    'Mecha: PRIME':[
        'draven',
        'jax',
        'leona',
        'sett',
        'wukong',
    ],
    'Ox Force':[
        'alistar',
        'annie',
        'aphelios',
        'fiora',
        'talon',
        'viego',
    ],
    'Star Guardian':[
        'ekko',
        'kaisa',
        'lux',
        'nilah',
        'rell',
        'syndra',
        'taliyah',
        'yuumi',
    ],
    'Supers':[
        'gp',
        'leesin',
        'malphite',
    ],
    'Threat':[
        'asol',
        'belveth',
        'chogath',
        'fiddle',
        'rammus',
        'urgot',
        'velkoz',
        'zac',
    ],
    'The Underground':[
        'ezreal',
        'kayle',
        'samira',
        'sona',
        'vi',
    ],
    'Ace':[
        'draven',
        'mf',
        'mord',
        'samira',
    ],
    'Aegis':[
        'alistar',
        'ekko',
        'leona',
        'vi',
    ],
    'Arsenal':[
        'aphelios',
    ],
    'Brawler':[
        'blitz',
        'jax',
        'leesin',
        'renekton',
        'riven',
        'sejuani',
        'vi',
    ],
    'Defender':[
        'poppy',
        'rell',
        'riven',
        'sett',
        'wukong',
    ],
    'Duelist':[
        'fiora',
        'gp',
        'kayle',
        'nilah',
        'vayne',
        'yasuo',
        'zed',
    ],
    'Forecaster':[
        'janna',
    ],
    'Hacker':[
        'leblanc',
        'zed',
        'zoe',
    ],
    'Heart':[
        'leesin',
        'lulu',
        'sona',
        'soraka',
        'syndra',
        'yuumi',
    ],
    'Mascot':[
        'alistar',
        'galio',
        'malphite',
        'nasus',
        'nunu',
        'yuumi',
    ],
    'Prankster':[
        'ekko',
        'jinx',
        'zoe',
    ],
    'Recon':[
        'ashe',
        'ezreal',
        'kaisa',
        'vayne',
    ],
    'Renegade':[
        'camille',
        'leona',
        'sylas',
        'talon',
        'viego',
    ],
    'Spellslinger':[
        'annie',
        'janna',
        'leblanc',
        'lux',
        'sona',
        'taliyah',
    ],
    'Sureshot':[
        'aphelios',
        'samira',
        'senna',
        'sivir',
    ],
}

champions_data = {
    'ashe':{
        'name':'Ashe',
        'cost': 1,
        'thumb':'ashe.png',
    },
    'blitz':{
        'name':'Blitzcrank',
        'cost': 1,
        'thumb':'blitz.png',
    },
    'galio':{
        'name':'Galio',
        'cost': 1,
        'thumb':'galio.png',
    },
    'gp':{
        'name':'Gangplank',
        'cost': 1,
        'thumb':'gp.png',
    },
    'kayle':{
        'name':'Kayle',
        'cost': 1,
        'thumb':'kayle.png',
    },
    'lulu':{
        'name':'Lulu',
        'cost': 1,
        'thumb':'lulu.png',
    },
    'lux':{
        'name':'Lux',
        'cost': 1,
        'thumb':'lux.png',
    },
    'nasus':{
        'name':'Nasus',
        'cost': 1,
        'thumb':'nasus.png',
    },
    'poppy':{
        'name':'Poppy',
        'cost': 1,
        'thumb':'poppy.png',
    },
    'renekton':{
        'name':'Renekton',
        'cost': 1,
        'thumb':'renekton.png',
    },
    'sylas':{
        'name':'Sylas',
        'cost': 1,
        'thumb':'sylas.png',
    },
    'talon':{
        'name':'Talon',
        'cost': 1,
        'thumb':'talon.png',
    },
    'wukong':{
        'name':'Wukong',
        'cost': 1,
        'thumb':'wukong.png',
    },
    'annie':{
        'name':'Annie',
        'cost': 2,
        'thumb':'annie.png',
    },
    'camille':{
        'name':'Camille',
        'cost': 2,
        'thumb':'camille.png',
    },
    'draven':{
        'name':'Draven',
        'cost': 2,
        'thumb':'draven.png',
    },
    'ezreal':{
        'name':'Ezreal',
        'cost': 2,
        'thumb':'ezreal.png',
    },
    'fiora':{
        'name':'Fiora',
        'cost': 2,
        'thumb':'fiora.png',
    },
    'jinx':{
        'name':'Jinx',
        'cost': 2,
        'thumb':'jinx.png',
    },
    'leesin':{
        'name':'Lee Singa',
        'cost': 2,
        'thumb':'leesin.png',
    },
    'malphite':{
        'name':'Malphite',
        'cost': 2,
        'thumb':'malphite.png',
    },
    'rell':{
        'name':'Rell',
        'cost': 2,
        'thumb':'rell.png',
    },
    'sivir':{
        'name':'Sivir',
        'cost': 2,
        'thumb':'sivir.png',
    },
    'vi':{
        'name':'Vi',
        'cost': 2,
        'thumb':'vi.png',
    },
    'yasuo':{
        'name':'Yasuo',
        'cost': 2,
        'thumb':'yasuo.png',
    },
    'yuumi':{
        'name':'Yuumi',
        'cost': 2,
        'thumb':'yuumi.png',
    },
    'alistar':{
        'name':'Alistar',
        'cost': 3,
        'thumb':'alistar.png',
    },
    'chogath':{
        'name':'Cho\'Gath',
        'cost': 3,
        'thumb':'chogath.png',
    },
    'jax':{
        'name':'Jax',
        'cost': 3,
        'thumb':'jax.png',
    },
    'kaisa':{
        'name':'Kai\'Sa',
        'cost': 3,
        'thumb':'kaisa.png',
    },
    'leblanc':{
        'name':'LeBlanc',
        'cost': 3,
        'thumb':'leblanc.png',
    },
    'nilah':{
        'name':'Nilah',
        'cost': 3,
        'thumb':'nilah.png',
    },
    'rammus':{
        'name':'Rammus',
        'cost': 3,
        'thumb':'rammus.png',
    },
    'riven':{
        'name':'Riven',
        'cost': 3,
        'thumb':'riven.png',
    },
    'senna':{
        'name':'Senna',
        'cost': 3,
        'thumb':'senna.png',
    },
    'sona':{
        'name':'Sona',
        'cost': 3,
        'thumb':'sona.png',
    },
    'vayne':{
        'name':'Vayne',
        'cost': 3,
        'thumb':'vayne.png',
    },
    'velkoz':{
        'name':'Vel\'Koz',
        'cost': 3,
        'thumb':'velkoz.png',
    },
    'zoe':{
        'name':'Zoe',
        'cost': 3,
        'thumb':'zoe.png',
    },
    'asol':{
        'name':'Aurelion Sol',
        'cost': 4,
        'thumb':'asol.png',
    },
    'belveth':{
        'name':'Bel\'Veth',
        'cost': 4,
        'thumb':'belveth.png',
    },
    'ekko':{
        'name':'Ekko',
        'cost': 4,
        'thumb':'ekko.png',
    },
    'mf':{
        'name':'Miss Fortune',
        'cost': 4,
        'thumb':'mf.png',
    },
    'samira':{
        'name':'Samira',
        'cost': 4,
        'thumb':'samira.png',
    },
    'sejuani':{
        'name':'Shejuani',
        'cost': 4,
        'thumb':'sejuani.png',
    },
    'sett':{
        'name':'Republican Candidate Sett',
        'cost': 4,
        'thumb':'sett.png',
    },
    'soraka':{
        'name':'Soraka Flocka Flame',
        'cost': 4,
        'thumb':'soraka.png',
    },
    'taliyah':{
        'name':'Taliyah',
        'cost': 4,
        'thumb':'taliyah.png',
    },
    'viego':{
        'name':'Viego',
        'cost': 4,
        'thumb':'viego.png',
    },
    'zac':{
        'name':'Zac',
        'cost': 4,
        'thumb':'zac.png',
    },
    'zed':{
        'name':'Zed',
        'cost': 4,
        'thumb':'zed.png',
    },
    'aphelios':{
        'name':'Aphelios',
        'cost': 5,
        'thumb':'aphelios.png',
    },
    'fiddle':{
        'name':'Fiddlesticks',
        'cost': 5,
        'thumb':'fiddle.png',
    },
    'janna':{
        'name':'Janna',
        'cost': 5,
        'thumb':'janna.png',
    },
    'leona':{
        'name':'Leona',
        'cost': 5,
        'thumb':'leona.png',
    },
    'mord':{
        'name':'Mordekaiser#1',
        'cost': 5,
        'thumb':'mord.png',
    },
    'nunu':{
        'name':'Nunu',
        'cost': 5,
        'thumb':'nunu.png',
    },
    'syndra':{
        'name':'Syndra',
        'cost': 5,
        'thumb':'syndra.png',
    },
    'urgot':{
        'name':'Urgot',
        'cost': 5,
        'thumb':'urgot.png',
    },     
}