origins = {
    'Academy':[
        'ezreal',
        'heimerdinger',
        'jayce',
        'leona',
        'lux',
    ],
    'Automata':[
        'amumu',
        'blitzcrank',
        'kog',
        'malzahar',
        'nocturne',
    ],
    'Black Rose':[
        'cass',
        'elise',
        'leblanc',
        'morgana',
        'vlad',
    ],
    'Chem-Baron':[
        'renata',
        'renni',
        'sevika',
        'silco',
        'singed',
        'smeech',
    ],
    'Conqueror':[
        'ambessa',
        'darius',
        'draven',
        'mordekaiser',
        'rell',
        'swain',
    ],
    'Emissary':[
        'ambessa',
        'garen',
        'nami',
        'tristana',
    ],
    'Enforcer':[
        'caitlyn',
        'camille',
        'loris',
        'maddie',
        'smeb',
        'tf',
        'vi',
    ],
    'Experiment':[
        'mundo',
        'nunu',
        'twitch',
        'urgot',
        'zyra',
    ],
    'Family':[
        'powder',
        'vander',
        'violet',
    ],
    'Firelight':[
        'ekko',
        'scar',
        'zeri',
    ],
    'High Roller':[
        'sevika',
    ],
    'Junker King':[
        'rumble',
    ],
    'Rebel':[
        'akali',
        'ezreal',
        'illaoi',
        'irelia',
        'jinx',
        'rcs',
        'vex',
        'zoe',
    ],
    'Scrap':[
        'corki',
        'ekko',
        'gangplank',
        'powder',
        'rumble',
        'trundle',
        'ziggs',
    ],
}

classes = {
    'Ambusher':[
        'camille',
        'ekko',
        'jinx',
        'powder',
        'smeech',
    ],
    'Artillerist':[
        'corki',
        'ezreal',
        'tristana',
        'urgot',
    ],
    'Bruiser':[
        'elise',
        'nunu',
        'renni',
        'rcs',
        'smeb',
        'trundle',
    ],
    'Dominator':[
        'blitzcrank',
        'cass',
        'mundo',
        'mordekaiser',
        'silco',
        'ziggs',
    ],
    'Form Swapper':[
        'elise',
        'gangplank',
        'jayce',
        'swain',
    ],
    'Pit Fighter':[
        'draven',
        'gangplank',
        'sevika',
        'urgot',
        'vi',
        'violet',
    ],
    'Quickstriker':[
        'akali',
        'ambessa',
        'nocturne',
        'tf',
    ],
    'Sentinel':[
        'illaoi',
        'irelia',
        'leona',
        'loris',
        'rell',
        'rumble',
        'singed',
    ],
    'Sniper':[
        'caitlyn',
        'kog',
        'maddie',
        'twitch',
        'zeri',
    ],
    'Sorcerer':[
        'leblanc',
        'lux',
        'nami',
        'swain',
        'vlad',
        'zoe',
        'zyra',
    ],
    'Visionary':[
        'heimerdinger',
        'malzahar',
        'morgana',
        'nunu',
        'rell',
        'renata',
        'vex',
    ],
    'Watcher':[
        'amumu',
        'darius',
        'garen',
        'scar',
        'vander',
        'vlad',
    ],
}

low_pop_traits = [
    'High Roller',
    'Junker King',
]


champions_data = {
    'amumu':{
        'name':'Amumu',
        'cost': 1,
        'thumb':'Amumu.png',
    },
    'darius':{
        'name':'Darius',
        'cost': 1,
        'thumb':'Darius.png',
    },
    'draven':{
        'name':'Draven',
        'cost': 1,
        'thumb':'Draven.png',
    },
    'irelia':{
        'name':'Irelia',
        'cost': 1,
        'thumb':'Irelia.png',
    },
    'lux':{
        'name':'Lux',
        'cost': 1,
        'thumb':'Lux.png',
    },
    'maddie':{
        'name':'Maddie',
        'cost': 1,
        'thumb':'Maddie.png',
    },
    'morgana':{
        'name':'Morgana',
        'cost': 1,
        'thumb':'Morgana.png',
    },
    'powder':{
        'name':'Powder',
        'cost': 1,
        'thumb':'Powder.png',
    },
    'singed':{
        'name':'Singed',
        'cost': 1,
        'thumb':'Singed.png',
    },
    'smeb':{
        'name':'Smeb',
        'cost': 1,
        'thumb':'Smeb.png',
    },
    'trundle':{
        'name':'Trundle',
        'cost': 1,
        'thumb':'Trundle.png',
    },
    'vex':{
        'name':'Vex',
        'cost': 1,
        'thumb':'Vex.png',
    },
    'violet':{
        'name':'Violet',
        'cost': 1,
        'thumb':'Violet.png',
    },
    'zyra':{
        'name':'Zyra',
        'cost': 1,
        'thumb':'Zyra.png',
    },
    'akali':{
        'name':'Akali',
        'cost': 2,
        'thumb':'Akali.png',
    },
    'camille':{
        'name':'Camille',
        'cost': 2,
        'thumb':'Camille.png',
    },
    'leona':{
        'name':'Leona',
        'cost': 2,
        'thumb':'Leona.png',
    },
    'nocturne':{
        'name':'Nocturne',
        'cost': 2,
        'thumb':'Nocturne.png',
    },
    'rell':{
        'name':'Rell',
        'cost': 2,
        'thumb':'Rell.png',
    },
    'renata':{
        'name':'Renata',
        'cost': 2,
        'thumb':'Renata.png',
    },
    'rcs':{
        'name':'RCS',
        'cost': 2,
        'thumb':'Sett.png',
    },
    'tristana':{
        'name':'Tristana',
        'cost': 2,
        'thumb':'Tristana.png',
    },
    'urgot':{
        'name':'Urgot',
        'cost': 2,
        'thumb':'Urgot.png',
    },
    'vander':{
        'name':'Vander',
        'cost': 2,
        'thumb':'Vander.png',
    },
    'vlad':{
        'name':'Vlad',
        'cost': 2,
        'thumb':'Vladimir.png',
    },
    'zeri':{
        'name':'Zeri',
        'cost': 2,
        'thumb':'Zeri.png',
    },
    'ziggs':{
        'name':'Ziggs',
        'cost': 2,
        'thumb':'Ziggs.png',
    },
    'blitzcrank':{
        'name':'Blitzcrank',
        'cost': 3,
        'thumb':'Blitzcrank.png',
    },
    'cass':{
        'name':'Cass',
        'cost': 3,
        'thumb':'Cassiopeia.png',
    },
    'ezreal':{
        'name':'Ezreal',
        'cost': 3,
        'thumb':'Ezreal.png',
    },
    'gangplank':{
        'name':'Gangplank',
        'cost': 3,
        'thumb':'Gangplank.png',
    },
    'kog':{
        'name':'Kog\'Maw',
        'cost': 3,
        'thumb':'Kogmaw.png',
    },
    'loris':{
        'name':'Loris',
        'cost': 3,
        'thumb':'Loris.png',
    },
    'nami':{
        'name':'Nami',
        'cost': 3,
        'thumb':'Nami.png',
    },
    'nunu':{
        'name':'Nunu',
        'cost': 3,
        'thumb':'Nunu.png',
    },
    'renni':{
        'name':'Renni',
        'cost': 3,
        'thumb':'renni.png',
    },
    'scar':{
        'name':'Scar',
        'cost': 3,
        'thumb':'Scar.png',
    },
    'smeech':{
        'name':'Smeech',
        'cost': 3,
        'thumb':'Smeech.png',
    },
    'swain':{
        'name':'Swain',
        'cost': 3,
        'thumb':'Swain.png',
    },
    'tf':{
        'name':'TF',
        'cost': 3,
        'thumb':'tf.png',
    },
    'ambessa':{
        'name':'Ambessa',
        'cost': 4,
        'thumb':'Ambessa.png',
    },
    'corki':{
        'name':'Corki',
        'cost': 4,
        'thumb':'Corki.png',
    },
    'mundo':{
        'name':'Mundo',
        'cost': 4,
        'thumb':'DrMundo.png',
    },
    'ekko':{
        'name':'Ekko',
        'cost': 4,
        'thumb':'Ekko.png',
    },
    'elise':{
        'name':'Elise',
        'cost': 4,
        'thumb':'Elise.png',
    },
    'garen':{
        'name':'Garen',
        'cost': 4,
        'thumb':'Garen.png',
    },
    'heimerdinger':{
        'name':'Heimerdinger',
        'cost': 4,
        'thumb':'Heimerdinger.png',
    },
    'illaoi':{
        'name':'Illaoi',
        'cost': 4,
        'thumb':'Illaoi.png',
    },
    'silco':{
        'name':'Silco',
        'cost': 4,
        'thumb':'Silco.png',
    },
    'twitch':{
        'name':'Twitch',
        'cost': 4,
        'thumb':'Twitch.png',
    },
    'vi':{
        'name':'Vi',
        'cost': 4,
        'thumb':'Vi.png',
    },
    'zoe':{
        'name':'Zoe',
        'cost': 4,
        'thumb':'zoe.png',
    },
    'caitlyn':{
        'name':'Caitlyn',
        'cost': 5,
        'thumb':'Caitlyn.png',
    },
    'jayce':{
        'name':'Jayce',
        'cost': 5,
        'thumb':'Jayce.png',
    },
    'jinx':{
        'name':'Jinx',
        'cost': 5,
        'thumb':'Jinx.png',
    },
    'leblanc':{
        'name':'LeBlanc',
        'cost': 5,
        'thumb':'Leblanc.png',
    },
    'malzahar':{
        'name':'Malzahar',
        'cost': 5,
        'thumb':'Malzahar.png',
    },
    'mordekaiser':{
        'name':'Mordekaiser',
        'cost': 5,
        'thumb':'Mordekaiser.png',
    },
    'rumble':{
        'name':'Rumble',
        'cost': 5,
        'thumb':'Rumble.png',
    },
    'sevika':{
        'name':'Sevika',
        'cost': 5,
        'thumb':'Sevika.png',
    },
}
