origins = [
    'A.D.M.I.N',
    'Anima Squad',
    'Gadgeteen',
    'InfiniTeam',
    'LaserCorps',
    'Mecha: PRIME',
    'Ox Force',
    'Riftwalker',
    'Star Guardian',
    'Supers',
    'Threat',
    'The Underground',
]
classes = [
    'Ace',
    'Aegis',
    'Brawler',
    'Defender',
    'Duelist',
    'Hacker',
    'Heart',
    'Mascot',
    'Prankster',
    'Quickdraw',
    'Renegade',
    'Spellslinger',
    'Sureshot',
]
low_pop_traits = [
    'Forecaster',
    'Corrupted',
    'Parallel',
]
trait_champions = {
    'A.D.M.I.N':[
        'blitz',
        'camille',
        'leblanc',
        'warwick',
    ],
    'Anima Squad':[
        'jinx',
        'mf',
        'nasus',
        'riven',
        'sylas',
        'vayne',
    ],
    'Corrupted':[
        'fiddle',
    ],
    'Forecaster':[
        'janna',
    ],    
    'Gadgeteen':[
        'annie',
        'gnar',        
        'lulu',
        'nunu',
        'poppy',
    ],
    'InfiniTeam':[
        'lucian',
        'pantheon',
        'shen',
        'sivir',
        'tf',
        'ult_ez',
    ],
    'LaserCorps':[
        'ashe',
        'mord',
        'renekton',
        'warwick',
        'yasuo',
    ],
    'Mecha: PRIME':[
        'draven',
        'garen',
        'jax',
        'leona',
        'wukong',
    ],
    'Ox Force':[
        'alistar',
        'annie',
        'fiora',
        'viego',
    ],
    'Parallel':[
        'ezreal',
        'ult_ez',
    ],
    'Riftwalker':[
        'jhin',
        'pyke',
        'vex'
    ],
    'Star Guardian':[
        'ekko',
        'kaisa',
        'lux',
        'neeko',
        'nilah',
        'rell',
        'syndra',
    ],
    'Supers':[
        'gp',
        'leesin',
        'malphite',
    ],
    'Threat':[
        'aatrox',
        'asol',
        'belveth',
        'fiddle',
        'morgana',
        'rammus',
        'urgot',
    ],
    'The Underground':[
        'ezreal',
        'kayle',
        'samira',
        'sona',
        'vi',
    ],
    'Ace':[
        'draven',
        'mf',
        'mord',
        'samira',
    ],
    'Aegis':[
        'alistar',
        'ekko',
        'leona',
        'vi',
    ],
    'Brawler':[
        'blitz',
        'jax',
        'leesin',
        'renekton',
        'riven',
        'vi',
        'warwick',
    ],
    'Defender':[
        'garen',
        'poppy',
        'rell',
        'riven',
        'shen',
        'wukong',
    ],
    'Duelist':[
        'fiora',
        'gp',
        'kayle',
        'nilah',
        'tf',
        'vayne',
        'yasuo',
    ],
    'Hacker':[
        'leblanc',
        'pyke',
        'shen',
    ],
    'Heart':[
        'leesin',
        'lulu',
        'pantheon',
        'sona',
        'syndra',
        'viego',
    ],
    'Mascot':[
        'alistar',
        'malphite',
        'nasus',
        'nunu',
        'vex',
    ],
    'Prankster':[
        'ekko',
        'gnar',
        'jinx',
    ],
    'Quickdraw':[
        'ezreal',
        'kaisa',
        'lucian',
        'mf',
    ],
    'Renegade':[
        'camille',
        'jhin',
        'leona',
        'lucian',
        'sylas',
        'viego',
    ],
    'Spellslinger':[
        'annie',
        'janna',
        'leblanc',
        'lux',
        'neeko',
        'sona',
        'tf',
    ],
    'Sureshot':[
        'ashe',
        'samira',
        'sivir',
        'ult_ez',
    ],
}

champions_data = {
    'ashe':{
        'name':'Ashe',
        'cost': 1,
        'thumb':'ashe.png',
    },
    'blitz':{
        'name':'Blitzcrank',
        'cost': 1,
        'thumb':'blitz.png',
    },
    'gp':{
        'name':'Gangplank',
        'cost': 1,
        'thumb':'gp.png',
    },
    'kayle':{
        'name':'Kayle',
        'cost': 1,
        'thumb':'kayle.png',
    },
    'lucian':{
        'name':'Lucian',
        'cost': 1,
        'thumb':'lucian.png',
    },
    'lulu':{
        'name':'Lulu',
        'cost': 1,
        'thumb':'lulu.png',
    },
    'lux':{
        'name':'Lux',
        'cost': 1,
        'thumb':'lux.png',
    },
    'nasus':{
        'name':'Nasus',
        'cost': 1,
        'thumb':'nasus.png',
    },
    'pantheon':{
        'name':'Pantheon',
        'cost': 1,
        'thumb':'pantheon.png',
    },
    'poppy':{
        'name':'Poppy',
        'cost': 1,
        'thumb':'poppy.png',
    },
    'renekton':{
        'name':'Renekton',
        'cost': 1,
        'thumb':'renekton.png',
    },
    'sylas':{
        'name':'Sylas',
        'cost': 1,
        'thumb':'sylas.png',
    },
    'wukong':{
        'name':'Wukong',
        'cost': 1,
        'thumb':'wukong.png',
    },
    'annie':{
        'name':'Annie',
        'cost': 2,
        'thumb':'annie.png',
    },
    'camille':{
        'name':'Camille',
        'cost': 2,
        'thumb':'camille.png',
    },
    'draven':{
        'name':'Draven',
        'cost': 2,
        'thumb':'draven.png',
    },
    'ezreal':{
        'name':'Ezreal',
        'cost': 2,
        'thumb':'ezreal.png',
    },
    'fiora':{
        'name':'Fiora',
        'cost': 2,
        'thumb':'fiora.png',
    },
    'jinx':{
        'name':'Jinx',
        'cost': 2,
        'thumb':'jinx.png',
    },
    'leesin':{
        'name':'Lee Singa',
        'cost': 2,
        'thumb':'leesin.png',
    },
    'malphite':{
        'name':'Malphite',
        'cost': 2,
        'thumb':'malphite.png',
    },
    'pyke':{
        'name':'Pyke',
        'cost': 2,
        'thumb':'pyke.png',
    },
    'rell':{
        'name':'Rell',
        'cost': 2,
        'thumb':'rell.png',
    },
    'sivir':{
        'name':'Sivir',
        'cost': 2,
        'thumb':'sivir.png',
    },
    'vi':{
        'name':'Vi',
        'cost': 2,
        'thumb':'vi.png',
    },
    'yasuo':{
        'name':'Yasuo',
        'cost': 2,
        'thumb':'yasuo.png',
    },
    'alistar':{
        'name':'Alistar',
        'cost': 3,
        'thumb':'alistar.png',
    },
    'gnar':{
        'name':'Gnar',
        'cost': 3,
        'thumb':'gnar.png',
    },
    'jax':{
        'name':'Jax',
        'cost': 3,
        'thumb':'jax.png',
    },
    'kaisa':{
        'name':'Kai\'Sa',
        'cost': 3,
        'thumb':'kaisa.png',
    },
    'leblanc':{
        'name':'LeBlanc',
        'cost': 3,
        'thumb':'leblanc.png',
    },
    'morgana':{
        'name':'Morgana',
        'cost': 3,
        'thumb':'morgana.png',
    },
    'nilah':{
        'name':'Nilah',
        'cost': 3,
        'thumb':'nilah.png',
    },
    'rammus':{
        'name':'Rammus',
        'cost': 3,
        'thumb':'rammus.png',
    },
    'riven':{
        'name':'Riven',
        'cost': 3,
        'thumb':'riven.png',
    },
    'shen':{
        'name':'Shen',
        'cost': 3,
        'thumb':'shen.png',
    },
    'sona':{
        'name':'Sona',
        'cost': 3,
        'thumb':'sona.png',
    },
    'vayne':{
        'name':'Vayne',
        'cost': 3,
        'thumb':'vayne.png',
    },
    'vex':{
        'name':'Vex',
        'cost': 3,
        'thumb':'vex.png',
    },
    'aatrox':{
        'name':'Aatrox',
        'cost': 4,
        'thumb':'aatrox.png',
    },
    'asol':{
        'name':'Aurelion Sol',
        'cost': 4,
        'thumb':'asol.png',
    },
    'belveth':{
        'name':'Bel\'Veth',
        'cost': 4,
        'thumb':'belveth.png',
    },
    'ekko':{
        'name':'Ekko',
        'cost': 4,
        'thumb':'ekko.png',
    },
    'garen':{
        'name':'Garen',
        'cost': 4,
        'thumb':'garen.png',
    },
    'jhin':{
        'name':'Jhin',
        'cost': 4,
        'thumb':'jhin.png',
    },
    'mf':{
        'name':'Miss Fortune',
        'cost': 4,
        'thumb':'mf.png',
    },
    'neeko':{
        'name':'Neeko',
        'cost': 4,
        'thumb':'neeko.png',
    },
    'samira':{
        'name':'Samira',
        'cost': 4,
        'thumb':'samira.png',
    },
    'tf':{
        'name':'Twisted Fate',
        'cost': 4,
        'thumb':'tf.png',
    },
    'viego':{
        'name':'Viego',
        'cost': 4,
        'thumb':'viego.png',
    },
    'warwick':{
        'name':'Warwick',
        'cost': 4,
        'thumb':'warwick.png',
    },
    'fiddle':{
        'name':'Fiddlesticks',
        'cost': 5,
        'thumb':'fiddle.png',
    },
    'janna':{
        'name':'Janna',
        'cost': 5,
        'thumb':'janna.png',
    },
    'leona':{
        'name':'Leona',
        'cost': 5,
        'thumb':'leona.png',
    },
    'mord':{
        'name':'Mordekaiser#1',
        'cost': 5,
        'thumb':'mord.png',
    },
    'nunu':{
        'name':'Nunu',
        'cost': 5,
        'thumb':'nunu.png',
    },
    'syndra':{
        'name':'Syndra',
        'cost': 5,
        'thumb':'syndra.png',
    },
    'ult_ez':{
        'name':'Ultimate Ezreal',
        'cost': 5,
        'thumb':'ult_ez.png',
    },
    'urgot':{
        'name':'Urgot',
        'cost': 5,
        'thumb':'urgot.png',
    },     
}